services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: freelancer_marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: pauliustechin/freelancer-marketplace-backend:latest
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/freelancer_marketplace
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: myTestSecret123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
      JWT_EXPIRATION_MS: 3600000
    ports:
      - "8080:8080"

  frontend:
    image: pauliustechin/freelancer-marketplace-frontend:latest
    restart: always
    ports:
      - "3000:80"

volumes:
  pgdata: