spring.application.name=freelancer-marketplace

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
#spring.jpa.show-sql=true

spring.app.jwtSecret=${JWT_SECRET}
spring.app.jwtExpirationMs=${JWT_EXPIRATION_MS}
spring.app.jwtCookieName=springSecurityCookie

frontend.url=${FRONTEND_URL}

spring.profiles.active=dev
